#!/bin/sh

snapshot_label=$(echo snapshot/c`hostname`/`date "+%Y-%m-%d_%H%M"`)
branch=$(git branch | grep \* | cut -d ' ' -f2)

# Check for dirty tree

# Discard branch
git checkout `git rev-parse HEAD`

# Force add everything
git add -f .

# Add everything to snapshot
git commit -m "Snapshot `date`"

# Create tag
git tag ${snapshot_label}

git reset --soft ${branch}
git checkout ${branch}
git reset

