#!/bin/sh

snapshot_label="snapshot/hostname/$(date +%Y-%m-%d_%H%M)"
branch=$(git branch | grep '\*' | cut -d ' ' -f2)

# Check for dirty tree

# check to make sure tag does not already exist
# or maybe just replace it.

# Also, maybe make it just give up if it sees submodules...

# Discard branch
git -c  advice.detachedHead=false checkout "$(git rev-parse HEAD)"

# Force add everything
git add -f "$@" $( [[ -z $@ ]] && echo "." )

# Add everything to snapshot
git commit -m "Snapshot $(date)"

# Create tag
git tag "${snapshot_label}"

git reset --soft "${branch}"
git checkout "${branch}"
git reset

